# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('desctiption', redactor.fields.RedactorField(max_length=1000, verbose_name='Описание')),
                ('text', redactor.fields.RedactorField(max_length=2000, verbose_name='Особенности')),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='SpecificationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('measure', models.CharField(blank=True, max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
            options={
                'verbose_name': 'Поле спецификации',
                'verbose_name_plural': 'Поля спецификации',
            },
        ),
        migrations.CreateModel(
            name='SpecificationInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
            options={
                'verbose_name': 'Экземпляр спецификации',
                'verbose_name_plural': 'Экземпляры спецификации',
            },
        ),
        migrations.CreateModel(
            name='SpecificationInstanceValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('specification_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SpecificationField')),
                ('specification_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SpecificationInstance')),
            ],
            options={
                'verbose_name': 'Значение поля спецификации',
                'verbose_name_plural': 'Значения полей спецификации',
            },
        ),
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('text', redactor.fields.RedactorField(max_length=3000, verbose_name='Текст')),
            ],
        ),
    ]
