# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 13:50
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desctiption',
            field=redactor.fields.RedactorField(max_length=3000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='text',
            field=redactor.fields.RedactorField(max_length=3000, verbose_name='Особенности'),
        ),
    ]
