# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160410_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationinstancevalue',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
