# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160411_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificationinstancevalue',
            name='value',
            field=models.CharField(max_length=1500),
        ),
    ]
