# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160411_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='specificationinstance',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
