# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_specificationinstance_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specificationinstance',
            options={'ordering': ['number'], 'verbose_name': 'Экземпляр спецификации', 'verbose_name_plural': 'Экземпляры спецификации'},
        ),
    ]
