# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160411_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification_image',
            field=models.ImageField(default=datetime.datetime(2016, 4, 25, 17, 46, 27, 76409, tzinfo=utc), upload_to='images/specifications'),
            preserve_default=False,
        ),
    ]
