# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_promoted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promoted_name',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
